export interface Horse {
    name: string;
    condition: number;
    color: string;
    traveledDistance: number;
    speed: number;
    run: boolean;
    finish: boolean;
    score: number;
  }

  export const horses: Horse[] = [
    {
      name: 'Marco',
      condition: 85,
      color: 'Yellow',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Apollo',
      condition: 90,
      color: 'Red',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Zeus',
      condition: 75,
      color: 'Blue',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Hercules',
      condition: 80,
      color: 'Green',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Ares',
      condition: 95,
      color: 'Purple',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Poseidon',
      condition: 88,
      color: 'Orange',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Hermes',
      condition: 70,
      color: 'Pink',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Athena',
      condition: 92,
      color: 'Brown',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Artemis',
      condition: 78,
      color: 'Black',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Hades',
      condition: 60,
      color: 'Gray',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Dionysus',
      condition: 82,
      color: 'Violet',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Helios',
      condition: 77,
      color: 'Gold',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Selene',
      condition: 89,
      color: 'Silver',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Eros',
      condition: 91,
      color: 'Teal',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Iris',
      condition: 79,
      color: 'Indigo',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Hephaestus',
      condition: 74,
      color: 'Turquoise',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Hera',
      condition: 87,
      color: 'Maroon',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Demeter',
      condition: 81,
      color: 'Lime',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Hestia',
      condition: 90,
      color: 'Crimson',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
    {
      name: 'Thor',
      condition: 85,
      color: 'White',
      traveledDistance: 0,
      speed: 0,
      run: false,
      finish: false,
      score: 0,
    },
  ];
